### PR TITLE
Rename redis-cache.iml to redis-cache.xml

### PR DESCRIPTION
**Pull request by szepeviktor**
@XedinUnknown Just that.

### CODE REVIEW

**Comment by XedinUnknown** [comment]
@szepeviktor, would you be able to explain the motivation for this change, please?

**Comment by szepeviktor** [comment]
Isn't `iml` extension a typo?

**Comment by szepeviktor** [comment]
I see! https://www.jetbrains.com/help/idea/creating-and-managing-modules.html 👁️ 
It is a "module file".

**Comment by XedinUnknown** [comment]
Yep! These things are generated and managed by PHPStorm via its interface and automations. Not something that should be renamed.

Thanks for the interest and support 🙏

**Pull request closed without merging**
